### ISSUE TITLE
RE figura incompatibility

### ISSUE THREAD

**Issue by LoogiCarry** [Traben-0/resource_explorer#2]
From what I've read in the log it disables essential gui and then crashes the game
![1190365358683603025](https://github.com/Traben-0/resource_explorer/assets/84445776/516c7e7d-b655-44f9-9483-d63fba8167b7)
[latest.log](https://github.com/Traben-0/resource_explorer/files/14075328/latest.log)

**Comment by Traben-0** [comment]
seems to be an incompatibility with one of figuras mixins

**Comment by Traben-0** [comment]
should be resolved in v1.1 when it's out
